//@version=5
indicator(title = "Bollinger Bands %B", shorttitle = "BB %B", format=format.price, precision=2, timeframe="", timeframe_gaps=true)
length = input.int(20, minval=1)
src = input(close, title="Source")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")
basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
bbr = (src - lower)/(upper - lower)
plot(bbr, "Bollinger Bands %B", color=#26A69A)
band1 = hline(1, "Overbought", color=#787B86, linestyle=hline.style_dashed)
hline(0.5, "Middle Band", color=color.new(#787B86, 50))
band0 = hline(0, "Oversold", color=#787B86, linestyle=hline.style_dashed)
fill(band1, band0, color=color.rgb(38, 166, 154, 90), title="Background")