//@version=5
indicator(title="Chaikin Oscillator", shorttitle="Chaikin Osc", format=format.volume, timeframe="", timeframe_gaps=true)
var cumVol = 0.
cumVol += nz(volume)
if barstate.islast and cumVol == 0
    runtime.error("No volume is provided by the data vendor.")
short = input.int(3, minval=1, title="Fast Length")
long = input.int(10, minval=1, title="Slow Length")
osc = ta.ema(ta.accdist, short) - ta.ema(ta.accdist, long)
plot(osc, title="Chaikin Oscillator", color=#EC407A)
hline(0, title="Zero", color=#787B86, linestyle=hline.style_dashed)