//@version=5
indicator(title="SMI Ergodic Oscillator", shorttitle="SMIO", format=format.price, precision=4, timeframe="", timeframe_gaps=true)
longlen = input.int(20, minval=1, title="Long Length")
shortlen = input.int(5, minval=1, title="Short Length")
siglen = input.int(5, minval=1, title="Signal Line Length")
erg = ta.tsi(close, shortlen, longlen)
sig = ta.ema(erg, siglen)
osc = erg - sig
plot(osc, color=#FF5252, style=plot.style_histogram, title="SMI Ergodic Oscillator")