//@version=5
strategy("Volty Expan Close Strategy", overlay=true)
length = input(5)
numATRs = input(0.75)
atrs = ta.sma(ta.tr, length)*numATRs
if (not na(close[length]))
	strategy.entry("VltClsLE", strategy.long, stop=close+atrs, comment = "VltClsLE")
	strategy.entry("VltClsSE", strategy.short, stop=close-atrs, comment = "VltClsSE")
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)